In [6]:
import os
os.chdir(r"D:\Code-Hero-Hub\PYTHON\Data Science\Python for Data Science\NPTEL Exam Prep\Week 3")

In [7]:
import numpy as np
import pandas as pd

In [8]:
data = pd.read_csv("hotel_bookings.csv")

In [9]:
data

,hotel,is_canceled,arrival_date_year,arrival_date_month,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,country,market_segment,is_repeated_guest,reserved_room_type,assigned_room_type,deposit_type,agent,company,customer_type,reservation_status,reservation_status_date
0,Resort Hotel,0,2015,July,1,0,0,2,0,PRT,Direct,0,C,C,No Deposit,NaN,NaN,Transient,Check-Out,2015-07-01
1,Resort Hotel,0,2015,July,1,0,0,2,0,PRT,Direct,0,C,C,No Deposit,NaN,NaN,Transient,Check-Out,2015-07-01
2,Resort Hotel,0,2015,July,1,0,1,1,0,GBR,Direct,0,A,C,No Deposit,NaN,NaN,Transient,Check-Out,2015-07-02
3,Resort Hotel,0,2015,July,1,0,1,1,0,GBR,Corporate,0,A,A,No Deposit,304.0,NaN,Transient,Check-Out,2015-07-02
4,Resort Hotel,0,2015,July,1,0,2,2,0,GBR,Online TA,0,A,A,No Deposit,240.0,NaN,Transient,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40055,City Hotel,0,2015,August,9,2,1,2,0,NOR,Online TA,0,A,A,No Deposit,9.0,NaN,Transient,Check-Out,2015-08-12
40056,City Hotel,0,2015,August,9,2,1,2,0,PRT,Offline TA/TO,0,B,B,No Deposit,3.0,NaN,Transient,Check-Out,2015-08-12
40057,City Hotel,0,2015,August,9,2,2,2,0,PRT,Online TA,0,A,D,No Deposit,9.0,NaN,Transient,Check-Out,2015-08-13
40058,City Hotel,0,2015,August,10,1,0,2,0,PRT,Online TA,0,A,A,No Deposit,9.0,NaN,Transient,Check-Out,2015-08-11
40059,City Hotel,0,2015,August,10,1,0,2,0,PRT,Online TA,0,A,A,No Deposit,9.0,NaN,Transient,Check-Out,2015-08-11

In [10]:
data.isnull().sum()

hotel                            0
is_canceled                      0
arrival_date_year                0
arrival_date_month               0
arrival_date_day_of_month        0
stays_in_weekend_nights          0
stays_in_week_nights             0
adults                           0
children                         0
country                        464
market_segment                   0
is_repeated_guest                0
reserved_room_type               0
assigned_room_type               0
deposit_type                     0
agent                         8213
company                      36951
customer_type                    0
reservation_status               0
reservation_status_date          0
dtype: int64

In [11]:
# Booking transcation in july
data.columns

Index(['hotel', 'is_canceled', 'arrival_date_year', 'arrival_date_month',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'country',
       'market_segment', 'is_repeated_guest', 'reserved_room_type',
       'assigned_room_type', 'deposit_type', 'agent', 'company',
       'customer_type', 'reservation_status', 'reservation_status_date'],
      dtype='object')

In [ ]:
# How many bookings were made by Transient-Party (customer type) in the month of July?

In [20]:
booking_in_july = data[(data["customer_type"] == "Transient-Party") &
                       (data["arrival_date_month"] == "July")].shape(0)

327

In [22]:
data.query("customer_type == 'Transient-Party' & arrival_date_month == 'July'").shape[0]

327